# Generated by Django 4.1.2 on 2023-05-04 14:33
from django.db import migrations, models

from ionos import settings


def clear_data(apps, _):
    test_upload_directory_model = apps.get_model('api', 'TestUploadDirectory')
    test_upload_directory_model.objects.all().delete()


def init_data(apps, _):
    test_upload_directory_model = apps.get_model('api', 'TestUploadDirectory')

    directories = []
    for base_dir in settings.TEST_BASE_DIRS:
        directories.append(test_upload_directory_model(directory=base_dir))
    test_upload_directory_model.objects.bulk_create(directories)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200706_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUploadDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('directory', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(init_data, reverse_code=clear_data)
    ]
